# Site settings
title: Simun Strukan
email: simun.strukan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/Users/Simun/Development/Web/Blog/_site/" # the subpath of your site, e.g. /blog/
url: "http://simun.strukan.website" # the base hostname & protocol for your site
twitter_username: Struki84
github_username:  Struki84

# Build settings
markdown: kramdown
# highlighter: rouge
